<a href="https://colab.research.google.com/github/Aayush1509-PROG/Cognitive-Computing-Assignments/blob/main/Assignment%205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 1D array with 5 elements
arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

# a) Addition of 2 in all elements
add_arr = arr + 2
print("a) After adding 2:", add_arr)

# b) Multiply 3 with all elements
mul_arr = arr * 3
print("b) After multiplying by 3:", mul_arr)

# c) Divide every element by 2
div_arr = arr / 2
print("c) After dividing by 2:", div_arr)


Original Array: [10 20 30 40 50]
a) After adding 2: [12 22 32 42 52]
b) After multiplying by 3: [ 30  60  90 120 150]
c) After dividing by 2: [ 5. 10. 15. 20. 25.]


In [2]:
import numpy as np

# a) Reverse the NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("a) Reversed array:", reversed_arr)


# b) Find the most frequent value and their indices
def find_most_frequent(arr_input):
    # bincount counts occurrences of non-negative integers
    counts = np.bincount(arr_input)
    most_frequent_val = np.argmax(counts)
    indices = np.where(arr_input == most_frequent_val)[0]
    return most_frequent_val, indices


# i. Array x
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
val_x, idx_x = find_most_frequent(x)
print(f"b) i. For array x: Most frequent value is {val_x} at indices {idx_x}")

# ii. Array y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
# Array y has a tie (1 and 3 both appear 3 times). Let's handle multiple modes:
counts_y = np.bincount(y)
max_count = np.max(counts_y)
modes = np.where(counts_y == max_count)[0]

for mode in modes:
    idx_y = np.where(y == mode)[0]
    print(
        f"b) ii. For array y: Most frequent value is {mode} at indices {idx_y}"
    )


a) Reversed array: [5 4 6 3 2 1]
b) i. For array x: Most frequent value is 1 at indices [0 5 7 8 9]
b) ii. For array y: Most frequent value is 1 at indices [0 1 2]
b) ii. For array y: Most frequent value is 3 at indices [4 8 9]


In [3]:
import numpy as np

# Creating the 2D array correctly
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# NumPy uses 0-based indexing
# a) Access 1st row (index 0), 2nd column (index 1)
elem_a = arr[0, 1]
print("a) Element at 1st row, 2nd column:", elem_a)

# b) Access 3rd row (index 2), 1st column (index 0)
elem_b = arr[2, 0]
print("b) Element at 3rd row, 1st column:", elem_b)


a) Element at 1st row, 2nd column: 20
b) Element at 3rd row, 1st column: 70


In [4]:
import numpy as np

# Replace 'Your_Name' with your actual name variable
your_name = np.linspace(10, 100, 25)
print("Array details:")
print("Dimensions (ndim):", your_name.ndim)
print("Shape:", your_name.shape)
print("Total elements (size):", your_name.size)
print("Data type (dtype):", your_name.dtype)
print("Total bytes consumed:", your_name.nbytes)

# Transpose using reshape() attribute
# Transposing a 1D array of shape (25,) requires converting it to a 2D shape like (25, 1) or (1, 25)
reshaped_transpose = your_name.reshape(-1, 1)
print("\nTranspose using reshape(-1, 1):\n", reshaped_transpose)

# Can we do the same with the .T attribute?
print("\nCan we use .T on 1D directly?")
print(
    "No, using your_name.T on a true 1D array returns the exact same 1D array: ",
    your_name.T.shape,
)
print(
    "To make .T work like a matrix transpose, we must first add an axis, e.g., your_name[np.newaxis, :].T"
)


Array details:
Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type (dtype): float64
Total bytes consumed: 200

Transpose using reshape(-1, 1):
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Can we use .T on 1D directly?
No, using your_name.T on a true 1D array returns the exact same 1D array:  (25,)
To make .T work like a matrix transpose, we must first add an axis, e.g., your_name[np.newaxis, :].T


In [5]:
import numpy as np

# 1. Create a 3x4 2D array
ucs420_your_name = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Original 3x4 Array:\n", ucs420_your_name)

# 2. Compute Statistics
print("\n--- Statistics ---")
print("Mean:", np.mean(ucs420_your_name))
print("Median:", np.median(ucs420_your_name))
print("Max:", np.max(ucs420_your_name))
print("Min:", np.min(ucs420_your_name))
print("Unique elements:", np.unique(ucs420_your_name))

# 3. Reshape array to 4 rows and 3 columns
reshaped_ucs420_your_name = ucs420_your_name.reshape(4, 3)
print("\n--- Reshaped Array (4x3) ---\n", reshaped_ucs420_your_name)

# 4. Resize array to 2 rows and 3 columns
# np.resize returns a new copy, truncating data if it doesn't fit
resized_ucs420_your_name = np.resize(ucs420_your_name, (2, 3))
print("\n--- Resized Array (2x3) ---\n", resized_ucs420_your_name)


Original 3x4 Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

--- Statistics ---
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

--- Reshaped Array (4x3) ---
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

--- Resized Array (2x3) ---
 [[10 20 30]
 [40 50 60]]
